[aliases.class]
TelegramDesktop = "Telegram"
"@polkadot/apps-electron" = "PolkadotJS"
"com\\.mitchellh\\.ghostty" = "Ghostty"

[aliases.instance]
"@polkadot/apps-electron" = "PolkadotJS"
"whatsapp.com" = "WhatsApp"
"chatgpt.com" = "ChatGPT"

[general]
empty_label = "ðŸŒ•"
display_property = "instance" # class, instance, name

